### ISSUE TITLE
File generated by template module writes to agent machine. 

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/hyperfoil_test#1]
Hi,
 The hyperfoil_test playbook uses the [template module to generate a filtered file from a template](https://github.com/Hyperfoil/hyperfoil_test/blob/master/tasks/main.yml#L4).
 The output file is stored not on the controller but on the agent.

 In the use case where the controller and agent are the same this is not an issue.

 In a distributed use case the hyperfoil_test play fails. When attempting to [Upload the benchmark template](https://github.com/Hyperfoil/hyperfoil_test/blob/master/tasks/main.yml#L4). The uri module is expecting the generated file to be present on the controller. I am seeing this error

> TASK [hyperfoil.hyperfoil_test : Upload benchmark template] *****************************************************************
> task path: /home/benchuser/.ansible/roles/hyperfoil.hyperfoil_test/tasks/main.yml:8
> <acmeclient2> ESTABLISH SSH CONNECTION FOR USER: None
> <acmeclient2> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/benchuser/.ansible/cp/eedfe41682 acmeclient2 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
> <acmeclient2> (0, '/home/benchuser\n', '')
> <acmeclient2> ESTABLISH SSH CONNECTION FOR USER: None
> <acmeclient2> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/benchuser/.ansible/cp/eedfe41682 acmeclient2 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/benchuser/.ansible/tmp/ansible-tmp-1566566172.1-112492023418465 `" && echo ansible-tmp-1566566172.1-112492023418465="` echo /home/benchuser/.ansible/tmp/ansible-tmp-1566566172.1-112492023418465 `" ) && sleep 0'"'"''
> <acmeclient2> (0, 'ansible-tmp-1566566172.1-112492023418465=/home/benchuser/.ansible/tmp/ansible-tmp-1566566172.1-112492023418465\n', '')
> <acmeclient2> ESTABLISH SSH CONNECTION FOR USER: None
> <acmeclient2> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/benchuser/.ansible/cp/eedfe41682 acmeclient2 '/bin/sh -c '"'"'rm -f -r /home/benchuser/.ansible/tmp/ansible-tmp-1566566172.1-112492023418465/ > /dev/null 2>&1 && sleep 0'"'"''
> <acmeclient2> (0, '', '')
> fatal: [acmeclient2]: FAILED! => {
>     "changed": false, 
>     "msg": "Could not find or access '/tmp/3scale-benchmark.yaml' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"
> }
> 	to retry, use: --limit @/home/benchuser/code/jboss_performance/Hyperfoil-test-runner-for-3Scale/ansible-hyperfoil-3scale-run.retry
> 
> PLAY RECAP ******************************************************************************************************************
> acmeclient2               : ok=3    changed=0    unreachable=0    failed=1   
>

**Comment by rvansa** [comment]
Turns out I had it fixed locally for a while but forgot to push it. Sorry, updated!
