### ISSUE TITLE
undefined variable issue when running tests

### ISSUE THREAD

**Issue by eguzki** [Hyperfoil/hyperfoil_test#10]
I am running into this issue when running tests:
```
fatal: [injector-benchmarks.dev.3sca.net]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: the inline if-expression on line 1 evaluated to false and no else section was defined.\n\nThe error appears to be in '/home/eguzki/.ansible/roles/hyperfoil.hyperfoil_test/tasks/main.yml': line 43, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  failed_when: curl_cmd.rc > 1\n- name: Start benchmark\n  ^ here\n"
}
```

It might be (not sure of course as I am not familiar with the codebase) related to this [commit](https://github.com/Hyperfoil/hyperfoil_test/commit/b8f4158766f65372521a42940714f6bc7b6f7f1e) from @rvansa . If I remove the condition added in the commit, the tests run successfully. 

Used task from https://github.com/3scale-labs/perftest-toolkit/blob/master/deployment/run.yml:
```
- hosts: hyperfoil_controller                
  roles:                                     
    - hyperfoil.hyperfoil_test               
  vars:                                      
    test_name: 3scale-benchmark              
    test_files:                              
      - "{{ csv_dest_file_path }}"           
    shared_connections: 10                   
    users_per_sec: 10                        
    duration_sec: 30                         
```

Ansible version
```
$ ansible-playbook --version
ansible-playbook 2.9.6
```

**Comment by rvansa** [comment]
Thanks, looks like Ansible does not suport the implicit `else undefined`.

**Comment by eguzki** [comment]
Hi, any update? it will be fixed?

**Comment by rvansa** [comment]
@eguzki Hi, sorry about neglecting this. Could you test if the fix in master works for you?

**Comment by eguzki** [comment]
The fix in master is working, thanks.

Looking forward to having a new release in the ansible galaxy community
