### ISSUE TITLE
Support for benchmark with multiple files in configuration.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/hyperfoil_test#3]
Attempting to upload a benchmark configuration fails on Hyperfoil 0.8-SNAPSHOT. The benchmark has this configured 
```
        - testSequence:
          - randomCsvRow:
             file: /tmp/3scale.csv
             skipComments: 'True'
```
which causes an error
```
TASK [hyperfoil.hyperfoil_test : Upload benchmark template] ******************************************************************
fatal: [server]: FAILED! => {"changed": false, "connection": "close", "content": "Cannot read benchmark: line 1, column 1: Expected DocumentStartEvent, got StreamEndEvent: <org.yaml.snakeyaml.events.StreamEndEvent()>", "content_length": "134", "msg": "Status code was 400 and not [204]: HTTP Error 400: Bad Request", "redirected": false, "status": 400, "url": "http://server:8090/benchmark"}
	to retry, use: --limit @/home/benchuser/jwhiting/3scale/perftest-toolkit-hf/deployment/run.retry

PLAY RECAP *******************************************************************************************************************
```

 The conditions for uploading a benchmark have changed over time. A benchmark should be "symmetrical" and self contained. This condition was added to the CsvRowStep in this [commit](https://github.com/Hyperfoil/Hyperfoil/commit/a8f69bc3b0edd8f8e9016d789f05efef8a1438ca).

 It means 2 files need uploading at the same time for the benchmark I have. Currently Ansible uri module does not support multi-part file uploads with defined field names. Which is a shame.

**Comment by rvansa** [comment]
I'll keep this open since I don't think #4 is a perfect fix (see comments there).
