### ISSUE TITLE
Ansible issue with conflicting action statements.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/hyperfoil_test#8]
Over on the perftest-toolkit project the adoption of Hyperfoil is seeing an issue. When running on an Ubuntu platform.
 A user is seeing an issue when the Ansible hyperfoil.hyperfoil_test role is executed. Mentioned in this [comment](https://github.com/3scale/perftest-toolkit/pull/34#issuecomment-664994195).
The Ansible error is copied here:

```
TASK [include_role : hyperfoil.hyperfoil_test] ***********************************************************************************************************************************************************************************************************************************
task path: /home/eguzki/git/perftest-toolkit2/deployment/run.yml:4
ERROR! conflicting action statements: shell, warn

The error appears to be in '/home/eguzki/.ansible/roles/hyperfoil.hyperfoil_test/tasks/main.yml': line 34, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    test_files: []
- name: Upload benchmark template
  ^ here
```

**Comment by rvansa** [comment]
It seems that there was wrong indentation (and placement), the `warn` belongs to `shell`. I've integrated #9 anyway.

**Comment by rvansa** [comment]
https://docs.ansible.com/ansible/latest/modules/shell_module.html#parameter-warn
